# -*- coding: utf-8 -*-
"""machine_failure_deployment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13M3h3iQjkHOfI8yLrc8LJ5Ay3sK6wHZz
"""

import streamlit as st
import pandas as pd
import joblib

model = joblib.load("machine_failure_prediction.pkl")

st.title("Machine Failure Prediction System")

st.write("you can enter the data from sensor and check whether your machine will work or fail under certain condition")

footfall = st.number_input("Footfall")
Temperature = st.number_input("Temperature")
USS = st.number_input("USS")
AQ = st.number_input("AQ")
CS = st.number_input("CS")
VOC = st.number_input("VOC")
RP = st.number_input("RP")
IP = st.number_input("IP")
tempMode = st.number_input("tempMode")

df = pd.DataFrame({
    "Footfall": [footfall],
    "tempMode": [tempMode],
    "AQ": [AQ],
    "USS": [USS],
    "CS": [CS],
    "VOC": [VOC],
    "RP": [RP],
    "IP": [IP],
    "Temperature": [Temperature]
})

if st.button("Predict"):
    prediction = model.predict(df)
    if prediction[0] ==1:
      st.error("Machine will fail")
    else:
      st.success("Machine will work")
